// AUTO-GENERATED by tools/hipfinufft/cuda_to_hip.py from test/cuda/test_makeplan.c
// Do not edit by hand. Edit the CUDA source and re-run the translator.
#include "finufft_errors.h"
#ifdef NDEBUG
#undef NDEBUG
#include <assert.h>
#define NDEBUG
#else
#include <assert.h>
#endif

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include <hip/hip_runtime.h>
#include <hipfinufft.h>

typedef struct {
  char *p[2];
} wasteful_pointers;

// hackish way to make allocation failures happen
wasteful_pointers alloc_remaining_device_mem() {
  wasteful_pointers a = {NULL, NULL};
  for (int i = 0; i < 2; ++i) {
    size_t free, total;
    hipMemGetInfo(&free, &total);

    int ier  = 1;
    int iter = 0;
    while (ier && (iter < 60)) {
      ier = hipMalloc((void **)&a.p[i], free - (1 << iter));
      iter++;
    }
  }

  return a;
}

void free_wasteful_pointers(wasteful_pointers a) {
  hipFree(a.p[0]);
  hipFree(a.p[1]);
}

int main() {
  hipfinufftf_plan plan;
  // defaults. tests should shadow them to override
  const int dim      = 1;
  const int type     = 1;
  const int iflag    = 1;
  const float tol    = 1e-5;
  const int ntransf  = 1;
  const int64_t N[3] = {10, 20, 15};

  // Dimension failure
  {
    const int dim = 0;
    assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, NULL) ==
           FINUFFT_ERR_DIM_NOTVALID);
    hipDeviceSynchronize();
  }

  // 1D failure modes
  {
    const int dim     = 1;
    const int type    = 1;
    const int ntransf = 1;

    // nice input should succeed
    assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, NULL) == 0);
    hipfinufftf_destroy(plan);
    hipDeviceSynchronize();

    // Ignore higher dims, even if invalid
    {
      int64_t N[3] = {10, 0, 15};
      assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, NULL) == 0);
      hipfinufftf_destroy(plan);
      hipDeviceSynchronize();
    }

    {
      int64_t N[3] = {0, 20, 15};
      assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, NULL) ==
             FINUFFT_ERR_NDATA_NOTVALID);
      hipDeviceSynchronize();
    }

    // hipfinufft can't handle arrays bigger than INT32_MAX (hipfft limitation)
    {
      int64_t N[3] = {(int64_t)INT32_MAX + 1, 1, 1};
      assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, NULL) ==
             FINUFFT_ERR_NDATA_NOTVALID);
      hipDeviceSynchronize();
    }

    {
      const int ntransf = 0;
      assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, NULL) ==
             FINUFFT_ERR_NTRANS_NOTVALID);
      hipDeviceSynchronize();
    }

    {
      const int type = 4;
      assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, NULL) ==
             FINUFFT_ERR_TYPE_NOTVALID);
      hipDeviceSynchronize();
    }

    /* { */
    /*     wasteful_pointers p = alloc_remaining_device_mem(); */
    /*     int64_t N[3] = {INT32_MAX, 1, 1}; */
    /*     assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, NULL)
     * == FINUFFT_ERR_HIP_FAILURE);
     */
    /*     free_wasteful_pointers(p); */
    /* } */
  }

  {
    const int dim = 2;
    assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, NULL) == 0);
    hipDeviceSynchronize();

    hipfinufftf_destroy(plan);

    {
      int64_t N[3] = {10, 0, 1};
      assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, NULL) ==
             FINUFFT_ERR_NDATA_NOTVALID);
      hipDeviceSynchronize();
    }

    // FIXME: nf calculation overflows -- need to handle upsampling mode calculation
    // properly
    /* { */
    /*     int64_t N[3] = {INT32_MAX / 2, 2, 1}; */
    /*     assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, NULL)
     * == 0); */
    /* } */

    {
      int64_t N[3] = {INT32_MAX, 2, 1};
      assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, NULL) ==
             FINUFFT_ERR_NDATA_NOTVALID);
      hipDeviceSynchronize();
    }

    {
      const int type = 4;
      assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, NULL) ==
             FINUFFT_ERR_TYPE_NOTVALID);
      hipDeviceSynchronize();
    }

    {
      const int ntransf = 0;
      assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, NULL) ==
             FINUFFT_ERR_NTRANS_NOTVALID);
      hipDeviceSynchronize();
    }

    {
      hipfinufft_opts opts;
      hipfinufft_default_opts(&opts);
      opts.upsampfac       = 0.9;
      opts.gpu_kerevalmeth = 1;
      assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, &opts) ==
             FINUFFT_ERR_HORNER_WRONG_BETA);

      opts.gpu_kerevalmeth = 0;
      assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, &opts) ==
             FINUFFT_ERR_UPSAMPFAC_TOO_SMALL);

      // Should produce a warning, not an error
      opts.upsampfac = 4.5;
      assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, &opts) == 0);
      hipfinufftf_destroy(plan);
      hipDeviceSynchronize();
    }

    // This technique to cause cuda failures works most of the time, but sometimes
    // would break following calls and could cause issues with other contexts using
    // the same GPU
    /* { */
    /*     wasteful_pointers p = alloc_remaining_device_mem(); */
    /*     int64_t N[3] = {sqrt(INT32_MAX - 1), sqrt(INT32_MAX) - 1, 1}; */
    /*     assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, NULL)
     * == FINUFFT_ERR_HIP_FAILURE);
     */
    /*     free_wasteful_pointers(p); */
    /* } */
  }

  {
    const int dim = 3;
    assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, NULL) == 0);
    hipfinufftf_destroy(plan);
    hipDeviceSynchronize();

    {
      int64_t N[3] = {10, 15, 0};
      assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, NULL) ==
             FINUFFT_ERR_NDATA_NOTVALID);
      hipDeviceSynchronize();
    }

    {
      int64_t N[3] = {INT32_MAX / 2, 2, 2};
      assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, NULL) ==
             FINUFFT_ERR_NDATA_NOTVALID);
      hipDeviceSynchronize();
    }

    {
      const int type = 4;
      assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, NULL) ==
             FINUFFT_ERR_TYPE_NOTVALID);
      hipDeviceSynchronize();
    }

    {
      const int ntransf = 0;
      assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, NULL) ==
             FINUFFT_ERR_NTRANS_NOTVALID);
      hipDeviceSynchronize();
    }

    /* { */
    /*     wasteful_pointers p = alloc_remaining_device_mem(); */
    /*     int64_t N[3] = {pow(INT32_MAX - 1, 1.0 / 3), pow(INT32_MAX - 1, 1.0 / 3),
     * pow(INT32_MAX - 1, 1.0 / 3)};
     */
    /*     assert(hipfinufftf_makeplan(type, dim, N, iflag, ntransf, tol, &plan, NULL)
     * == FINUFFT_ERR_HIP_FAILURE);
     */
    /*     free_wasteful_pointers(p); */
    /* } */
  }
}
