// AUTO-GENERATED by tools/hipfinufft/cuda_to_hip.py from include/cufinufft/common_kernels.hpp
// Do not edit by hand. Edit the CUDA source and re-run the translator.
#pragma once

#include <thrust/sequence.h>

#include <hipfinufft/common.h>
#include <hipfinufft/contrib/helper_hip.h>
#include <hipfinufft/contrib/helper_math.h>
#include <hipfinufft/intrinsics.h>
#include <hipfinufft/spreadinterp.h>
#include <hipfinufft/utils.h>

namespace hipfinufft {
namespace spreadinterp {

using namespace hipfinufft::utils;
using namespace hipfinufft::common;

// The only functions in this header that are called from outside are
// called "cu<spread/interp>_<method>[_prop]".
// All other functions are only used locally.

// Ubuntu HIP 7.1: HIP_vector_type::operator+= has an ambiguous overload set
// (member vs scalar-broadcast template). hip_complex<T> is an alias template,
// so template-argument deduction on it fails; template on the concrete vector
// type C directly so the compiler can deduce it.
template<typename C>
__host__ __device__ __forceinline__ void cadd(C& dst, C src) noexcept {
  dst.x += src.x;
  dst.y += src.y;
}

/* --------------------------- Shared Helpers ---------------------------- */

// Given grid sizes (via plan.nf123) and bin sizes, compute the number of bins
// along every axis.
template<int ndim, typename T>
auto get_nbins(const hipfinufft_plan_t<T> &plan, std::array<int, 3> binsizes) {
  std::array<int, 3> nbins{1, 1, 1};
  for (int idim = 0; idim < ndim; ++idim) {
    if (binsizes[idim] <= 0) {
      std::cerr << "[cuspread_nuptsdriven_prop] error: invalid binsize (dim " << idim
                << ") = (" << binsizes[idim] << ")\n";
      throw int(FINUFFT_ERR_BINSIZE_NOTVALID);
    }
    nbins[idim] = (plan.nf123[idim] + binsizes[idim] - 1) / binsizes[idim];
  }
  return nbins;
}

inline int nbins_total(const std::array<int, 3> &nbins) {
  return nbins[0] * nbins[1] * nbins[2];
}

// For the current nonuniform point (given via idx), compute the set of
// start indices of the spreading/interpolation area in the locally stored subgrid.
// Also compute the kernel values to use in spreading/interpolation.
template<typename T, int KEREVALMETH, int ndim, int ns>
__device__ auto get_kerval_and_local_start(
    int idx, std::array<const T *, 3> xyz, std::array<int, 3> nf,
    std::array<int, ndim> offset, T sigma, T es_c, T es_beta) {
  constexpr auto ns_2f = T(ns * .5);
  std::array<std::array<T, ns>, ndim> ker;
  std::array<int, ndim> start;
  for (int idim = 0; idim < ndim; ++idim) {
    const auto rescaled = fold_rescale(loadReadOnly(xyz[idim] + idx), nf[idim]);
    const auto s        = int(std::ceil(rescaled - ns_2f));
    if constexpr (KEREVALMETH == 1) {
      eval_kernel_vec_horner<T, ns>(&ker[idim][0], T(s) - rescaled, sigma);
    } else {
      eval_kernel_vec<T, ns>(&ker[idim][0], T(s) - rescaled, es_c, es_beta);
    }
    start[idim] = s - offset[idim];
  }
  return std::make_tuple(ker, start);
}

// For the current nonuniform point (given via idx), compute the set of
// start indices of the spreading/interpolation area in the locally stored subgrid.
// Also compute the kernel values to use in spreading/interpolation.
// (Version for nonunifom-points-driven algorithm.)
template<typename T, int KEREVALMETH, int ndim, int ns>
__device__ auto get_kerval_and_startpos_nuptsdriven(
    int idx, std::array<const T *, 3> xyz, std::array<int, 3> nf, T sigma,
    T es_c, T es_beta) {
  std::array<std::array<T, ns>, ndim> ker;
  std::array<int, ndim> start;
  for (size_t idim = 0; idim < ndim; ++idim) {
    auto rescaled   = fold_rescale(loadReadOnly(xyz[idim] + idx), nf[idim]);
    auto [s, dummy] = interval(ns, rescaled);
    if constexpr (KEREVALMETH == 1) {
      eval_kernel_vec_horner<T, ns>(&ker[idim][0], T(s) - rescaled, sigma);
    } else {
      eval_kernel_vec<T, ns>(&ker[idim][0], T(s) - rescaled, es_c, es_beta);
    }
    start[idim] = s + ((s < 0) ? nf[idim] : 0);
  }
  return std::make_tuple(ker, start);
}

template<int ndim>
__device__ auto compute_offset(int bidx, const std::array<int, 3> &nbins,
                               const std::array<int, 3> &binsizes) {
  std::array<int, ndim> offset;
  int tmp = bidx;
  for (int idim = 0; idim + 1 < ndim; ++idim) {
    offset[idim] = (tmp % nbins[idim]) * binsizes[idim];
    tmp /= nbins[idim];
  }
  // last dimension can be done more cheaply
  offset[ndim - 1] = tmp * binsizes[ndim - 1];
  return offset;
}

// For the current nonuniform point (given via idx), compute the flat index
// of the bin it falls into.
template<int ndim, typename T>
__device__ int compute_bin_index(
    int idx, std::array<int, 3> nf, std::array<T, 3> inv_binsizes,
    std::array<int, 3> nbins, std::array<const T *, 3> xyz) {
  int binidx = 0;
  int stride = 1;
  for (int idim = 0; idim < ndim; ++idim) {
    const T rescaled = fold_rescale(loadReadOnly(xyz[idim] + idx), nf[idim]);
    int bin          = floor(rescaled * inv_binsizes[idim]);
    bin              = bin >= nbins[idim] ? bin - 1 : bin;
    bin              = bin < 0 ? 0 : bin;
    binidx += bin * stride;
    stride *= nbins[idim];
  }
  return binidx;
}

// Given bin sizes and kernel support, compute the size of a padded subgrid.
template<int ndim, int ns>
__device__ auto get_padded_subgrid_info(const std::array<int, 3> &binsizes) {
  constexpr auto rounded_ns = ((ns + 1) / 2) * 2;
  std::array<int, ndim> padded_size;
  int total = 1;
  for (int idim = 0; idim < ndim; ++idim) {
    padded_size[idim] = binsizes[idim] + rounded_ns;
    total *= padded_size[idim];
  }
  return std::make_tuple(padded_size, total);
}

// Given a flat index in a local padded subgrid, compute its location in the global grid.
template<int ndim, int ns>
__device__ int output_index_from_flat_local_index(
    int flatidx, const std::array<int, ndim> &padded_size,
    const std::array<int, ndim> &offset, const std::array<int, 3> &nf) {
  constexpr auto ns_2 = (ns + 1) / 2;

  int outidx    = 0;
  int outstride = 1;
  for (int idim = 0; idim < ndim; ++idim) {
    int idx0 = flatidx % padded_size[idim];
    int idx  = idx0 + offset[idim] - ns_2;
    idx      = idx < 0 ? idx + nf[idim] : (idx >= nf[idim] ? idx - nf[idim] : idx);
    outidx += idx * outstride;
    outstride *= nf[idim];
    flatidx /= padded_size[idim];
  }
  return outidx;
}

/* ------------------------- Interpolation section ------------------------------ */

// Nupts-driven interpolation kernel
template<typename T, int KEREVALMETH, int ndim, int ns>
__global__ FINUFFT_FLATTEN void interp_nupts_driven(
    const std::array<const T *, 3> xyz, hip_complex<T> *FINUFFT_RESTRICT c,
    const hip_complex<T> *FINUFFT_RESTRICT fw, const int M,
    const std::array<int, 3> nf, const T es_c, const T es_beta, const T sigma,
    const int *FINUFFT_RESTRICT idxnupts) {

  for (int i = blockDim.x * blockIdx.x + threadIdx.x; i < M;
       i += blockDim.x * gridDim.x) {
    const auto nuptsidx = loadReadOnly(idxnupts + i);

    auto [ker, start] = get_kerval_and_startpos_nuptsdriven<T, KEREVALMETH, ndim, ns>(
        nuptsidx, xyz, nf, sigma, es_c, es_beta);

    hip_complex<T> cnow{0, 0};
    if constexpr (ndim == 1) {
      for (int x0 = 0, ix = start[0]; x0 < ns; ++x0, ix = (ix + 1 >= nf[0]) ? 0 : ix + 1)
        cadd(cnow, loadReadOnly(fw + ix) * ker[0][x0]);
    } else if constexpr (ndim == 2) {
      for (int y0 = 0, iy = start[1]; y0 < ns;
           ++y0, iy       = (iy + 1 >= nf[1]) ? 0 : iy + 1) {
        const auto inidx0 = iy * nf[0];
        hip_complex<T> cnowx{0, 0};
        for (int x0 = 0, ix = start[0]; x0 < ns;
             ++x0, ix       = (ix + 1 >= nf[0]) ? 0 : ix + 1)
          cadd(cnowx, loadReadOnly(fw + inidx0 + ix) * ker[0][x0]);
        cadd(cnow, cnowx * ker[1][y0]);
      }
    } else {
      std::array<int, ns> xidx;
      for (int x0 = 0, ix = start[0]; x0 < ns; ++x0, ix = (ix + 1 >= nf[0]) ? 0 : ix + 1)
        xidx[x0] = ix;
      for (int z0 = 0, iz = start[2]; z0 < ns;
           ++z0, iz       = (iz + 1 >= nf[2]) ? 0 : iz + 1) {
        const auto inidx0 = iz * nf[1] * nf[0];
        hip_complex<T> cnowy{0, 0};
        for (int y0 = 0, iy = start[1]; y0 < ns;
             ++y0, iy       = (iy + 1 >= nf[1]) ? 0 : iy + 1) {
          const auto inidx1 = inidx0 + iy * nf[0];
          hip_complex<T> cnowx{0, 0};
          for (int x0 = 0; x0 < ns; ++x0)
            cadd(cnowx, loadReadOnly(fw + inidx1 + xidx[x0]) * ker[0][x0]);
          cadd(cnowy, cnowx * ker[1][y0]);
        }
        cadd(cnow, cnowy * ker[2][z0]);
      }
    }
    storeCacheStreaming(c + nuptsidx, cnow);
  }
}

// Nupts-driven interpolation CPU driver
template<typename T, int ndim, int ns>
void cuinterp_nuptsdriven(const hipfinufft_plan_t<T> &d_plan, int blksize) {
  const T es_c    = 4.0 / T(d_plan.spopts.nspread * d_plan.spopts.nspread);
  const T es_beta = d_plan.spopts.beta;
  const T sigma   = d_plan.spopts.upsampfac;

  const dim3 threadsPerBlock{
      optimal_interp_block_threads(d_plan.opts.gpu_device_id, d_plan.M), 1u, 1u};
  const dim3 blocks{(d_plan.M + threadsPerBlock.x - 1) / threadsPerBlock.x, 1, 1};

  const auto launch = [&](auto kernel) {
    for (int t = 0; t < blksize; t++) {
      kernel<<<blocks, threadsPerBlock, 0, d_plan.stream>>>(
          d_plan.kxyz, d_plan.c + t * d_plan.M, d_plan.fw + t * d_plan.nf, d_plan.M,
          d_plan.nf123, es_c, es_beta, sigma, dethrust(d_plan.idxnupts));
      THROW_IF_HIP_ERROR
    }
  };
  if (d_plan.opts.gpu_kerevalmeth)
    launch(interp_nupts_driven<T, 1, ndim, ns>);
  else
    launch(interp_nupts_driven<T, 0, ndim, ns>);
}

// Iterates over all locations in a local subgrid, and for all pairs of
// corresponding local and global pixels, calls the provided function.
// Useful for copying between global and local grids.
template<typename T, int ndim, int ns, typename Func>
__device__ void shared_mem_copy_helper(std::array<int, 3> binsizes,
                                       std::array<int, ndim> offset,
                                       std::array<int, 3> nf, Func func) {
  constexpr auto ns_2 = (ns + 1) / 2;

  auto [padded_size, N] = get_padded_subgrid_info<ndim, ns>(binsizes);

  for (int n = threadIdx.x; n < N; n += blockDim.x) {
    bool in_region = true;
    int flatidx    = n;
    int globidx    = 0;
    int globstride = 1;
    for (int idim = 0; idim < ndim; ++idim) {
      int idx0 = flatidx % padded_size[idim];
      int idx  = idx0 + offset[idim] - ns_2;
      if (idx >= nf[idim] + ns_2) in_region = false;
      idx = idx < 0 ? idx + nf[idim] : (idx >= nf[idim] ? idx - nf[idim] : idx);
      globidx += idx * globstride;
      globstride *= nf[idim];
      flatidx /= padded_size[idim];
    }
    if (in_region)
      func(n, globidx); // atomicAddComplexGlobal<T>(fw + outidx, fwshared[n]);
  }
}

// Subprob interpolation kernel
template<typename T, int KEREVALMETH, int ndim, int ns>
__global__ FINUFFT_FLATTEN void interp_subprob(
    const std::array<const T *, 3> xyz, hip_complex<T> *FINUFFT_RESTRICT c,
    const hip_complex<T> *FINUFFT_RESTRICT fw, const int M,
    const std::array<int, 3> nf, const T es_c, const T es_beta, const T sigma,
    const int *FINUFFT_RESTRICT binstartpts, const int *FINUFFT_RESTRICT bin_size,
    const std::array<int, 3> binsizes, const int *FINUFFT_RESTRICT subprob_to_bin,
    const int *FINUFFT_RESTRICT subprobstartpts, const int *FINUFFT_RESTRICT numsubprob,
    const int maxsubprobsize, const std::array<int, 3> nbins,
    const int *FINUFFT_RESTRICT idxnupts) {
  extern __shared__ char sharedbuf[];
  auto fwshared = (hip_complex<T> *)sharedbuf;

  const auto subpidx     = blockIdx.x;
  const auto bidx        = loadReadOnly(subprob_to_bin + subpidx);
  const auto binsubp_idx = subpidx - loadReadOnly(subprobstartpts + bidx);
  const auto ptstart = loadReadOnly(binstartpts + bidx) + binsubp_idx * maxsubprobsize;
  const auto nupts =
      min(maxsubprobsize, loadReadOnly(bin_size + bidx) - binsubp_idx * maxsubprobsize);

  auto offset = compute_offset<ndim>(bidx, nbins, binsizes);

  constexpr auto ns_2       = (ns + 1) / 2;
  constexpr auto rounded_ns = ns_2 * 2;

  shared_mem_copy_helper<T, ndim, ns>(
      binsizes, offset, nf, [fw, fwshared](int idx_shared, int idx_global) {
        fwshared[idx_shared] = loadReadOnly(fw + idx_global);
      });
  __syncthreads();

  for (int i = threadIdx.x; i < nupts; i += blockDim.x) {
    const int idx       = ptstart + i;
    const auto nuptsidx = loadReadOnly(idxnupts + idx);
    auto [ker, start]   = get_kerval_and_local_start<T, KEREVALMETH, ndim, ns>(
        nuptsidx, xyz, nf, offset, sigma, es_c, es_beta);

    hip_complex<T> cnow{0, 0};
    if constexpr (ndim == 1) {
      const auto ofs0 = start[0] + ns_2;
      for (int xx = 0; xx < ns; ++xx) cadd(cnow, fwshared[ofs0 + xx] * ker[0][xx]);
    }
    if constexpr (ndim == 2) {
      const auto delta_y = binsizes[0] + rounded_ns;
      const auto ofs0    = (start[1] + ns_2) * delta_y + (start[0] + ns_2);
      for (int yy = 0; yy < ns; ++yy) {
        hip_complex<T> cnowy{0, 0};
        const auto ofs = ofs0 + yy * delta_y;
        for (int xx = 0; xx < ns; ++xx) {
          cadd(cnowy, fwshared[ofs + xx] * ker[0][xx]);
        }
        cadd(cnow, cnowy * ker[1][yy]);
      }
    }
    if constexpr (ndim == 3) {
      const auto delta_y = binsizes[0] + rounded_ns;
      const auto delta_z = delta_y * (binsizes[1] + rounded_ns);
      const auto ofs0 =
          (start[2] + ns_2) * delta_z + (start[1] + ns_2) * delta_y + (start[0] + ns_2);
      for (int zz = 0; zz < ns; ++zz) {
        hip_complex<T> cnowz{0, 0};
        const auto ofs1 = ofs0 + zz * delta_z;
        for (int yy = 0; yy < ns; ++yy) {
          hip_complex<T> cnowy{0, 0};
          const auto ofs = ofs1 + yy * delta_y;
          for (int xx = 0; xx < ns; ++xx) {
            cadd(cnowy, fwshared[ofs + xx] * ker[0][xx]);
          }
          cadd(cnowz, cnowy * ker[1][yy]);
        }
        cadd(cnow, cnowz * ker[2][zz]);
      }
    }
    storeCacheStreaming(c + nuptsidx, cnow);
  }
}

// Subprob interpolation CPU driver
template<typename T, int ndim, int ns>
void cuinterp_subprob(const hipfinufft_plan_t<T> &d_plan, int blksize) {
  const int maxsubprobsize = d_plan.opts.gpu_maxsubprobsize;

  std::array<int, 3> binsizes{d_plan.opts.gpu_binsizex, d_plan.opts.gpu_binsizey,
                                    d_plan.opts.gpu_binsizez};

  std::array<int, 3> numbins;
  for (int idim = 0; idim < ndim; ++idim)
    numbins[idim] = (d_plan.nf123[idim] + binsizes[idim] - 1) / binsizes[idim];

  const T sigma                = d_plan.spopts.upsampfac;
  const T es_c                 = 4.0 / T(d_plan.spopts.nspread * d_plan.spopts.nspread);
  const T es_beta              = d_plan.spopts.beta;
  const auto sharedplanorysize = shared_memory_required<T>(
      ndim, d_plan.spopts.nspread, d_plan.opts.gpu_binsizex, d_plan.opts.gpu_binsizey,
      d_plan.opts.gpu_binsizez, d_plan.opts.gpu_np);

  const auto launch = [&](auto kernel) {
    hipfinufft_set_shared_memory(kernel, ndim, d_plan);
    for (int t = 0; t < blksize; t++) {
      kernel<<<d_plan.totalnumsubprob, 256, sharedplanorysize, d_plan.stream>>>(
          d_plan.kxyz, d_plan.c + t * d_plan.M, d_plan.fw + t * d_plan.nf, d_plan.M,
          d_plan.nf123, es_c, es_beta, sigma, dethrust(d_plan.binstartpts),
          dethrust(d_plan.binsize), binsizes, dethrust(d_plan.subprob_to_bin),
          dethrust(d_plan.subprobstartpts), dethrust(d_plan.numsubprob), maxsubprobsize,
          numbins, dethrust(d_plan.idxnupts));
      THROW_IF_HIP_ERROR
    }
  };
  if (d_plan.opts.gpu_kerevalmeth)
    launch(interp_subprob<T, 1, ndim, ns>);
  else
    launch(interp_subprob<T, 0, ndim, ns>);
}

/* ------------------------- Spreading section ------------------------------ */

// Nupts-driven spreading kernel
template<typename T, int KEREVALMETH, int ndim, int ns>
__global__ FINUFFT_FLATTEN void spread_nupts_driven(
    const std::array<const T *, 3> xyz, const hip_complex<T> *FINUFFT_RESTRICT c,
    hip_complex<T> *FINUFFT_RESTRICT fw, const int M, const std::array<int, 3> nf,
    const T es_c, const T es_beta, const T sigma, const int *FINUFFT_RESTRICT idxnupts) {

  for (int i = blockDim.x * blockIdx.x + threadIdx.x; i < M;
       i += blockDim.x * gridDim.x) {
    const auto nuptsidx = loadReadOnly(idxnupts + i);
    auto [ker, start]   = get_kerval_and_startpos_nuptsdriven<T, KEREVALMETH, ndim, ns>(
        nuptsidx, xyz, nf, sigma, es_c, es_beta);

    const auto val = loadReadOnly(c + nuptsidx);
    if constexpr (ndim == 1) {
      for (int x0 = 0, ix = start[0]; x0 < ns; ++x0, ix = (ix + 1 >= nf[0]) ? 0 : ix + 1)
        atomicAddComplexGlobal<T>(fw + ix, ker[0][x0] * val);
    } else if constexpr (ndim == 2) {
      for (int y0 = 0, iy = start[1]; y0 < ns;
           ++y0, iy       = (iy + 1 >= nf[1]) ? 0 : iy + 1) {
        const auto outidx0   = iy * nf[0];
        hip_complex<T> valy = val * ker[1][y0];
        for (int x0 = 0, ix = start[0]; x0 < ns;
             ++x0, ix       = (ix + 1 >= nf[0]) ? 0 : ix + 1)
          atomicAddComplexGlobal<T>(fw + outidx0 + ix, ker[0][x0] * valy);
      }
    } else {
      for (int z0 = 0, iz = start[2]; z0 < ns;
           ++z0, iz       = (iz + 1 >= nf[2]) ? 0 : iz + 1) {
        const auto outidx0   = iz * nf[1] * nf[0];
        hip_complex<T> valz = val * ker[2][z0];
        for (int y0 = 0, iy = start[1]; y0 < ns;
             ++y0, iy       = (iy + 1 >= nf[1]) ? 0 : iy + 1) {
          const auto outidx1   = outidx0 + iy * nf[0];
          hip_complex<T> valy = valz * ker[1][y0];
          for (int x0 = 0, ix = start[0]; x0 < ns;
               ++x0, ix       = (ix + 1 >= nf[0]) ? 0 : ix + 1) {
            atomicAddComplexGlobal<T>(fw + outidx1 + ix, ker[0][x0] * valy);
          }
        }
      }
    }
  }
}

// Nupts-driven spreading CPU driver
template<typename T, int ndim, int ns>
void cuspread_nupts_driven(const hipfinufft_plan_t<T> &d_plan, int blksize) {
  const T sigma   = d_plan.spopts.upsampfac;
  const T es_c    = 4.0 / T(d_plan.spopts.nspread * d_plan.spopts.nspread);
  const T es_beta = d_plan.spopts.beta;

  const dim3 threadsPerBlock{16, 1, 1};
  const dim3 blocks{(unsigned(d_plan.M) + 15) / 16, 1, 1};

  const auto launch = [&](auto kernel) {
    for (int t = 0; t < blksize; t++) {
      kernel<<<blocks, threadsPerBlock, 0, d_plan.stream>>>(
          d_plan.kxyz, d_plan.c + t * d_plan.M, d_plan.fw + t * d_plan.nf, d_plan.M,
          d_plan.nf123, es_c, es_beta, sigma, dethrust(d_plan.idxnupts));
      THROW_IF_HIP_ERROR
    }
  };
  if (d_plan.opts.gpu_kerevalmeth)
    launch(spread_nupts_driven<T, 1, ndim, ns>);
  else
    launch(spread_nupts_driven<T, 0, ndim, ns>);
}

// FIXME unify the next two functions and templatize on a lambda?
template<typename T, int ndim>
__global__ FINUFFT_FLATTEN void calc_bin_size_noghost(
    const int M, const std::array<int, 3> nf,
    const std::array<T, 3> inv_binsizes, const std::array<int, 3> nbins,
    int *FINUFFT_RESTRICT bin_size, const std::array<const T *, 3> xyz,
    int *FINUFFT_RESTRICT sortidx) {
  for (int i = threadIdx.x + blockIdx.x * blockDim.x; i < M;
       i += gridDim.x * blockDim.x) {
    const int binidx = compute_bin_index<ndim>(i, nf, inv_binsizes, nbins, xyz);
    const int oldidx = atomicAdd(&bin_size[binidx], 1);
    storeCacheStreaming(sortidx + i, oldidx);
  }
}

template<typename T, int ndim>
__global__ FINUFFT_FLATTEN void calc_inverse_of_global_sort_idx(
    const int M, const std::array<T, 3> inv_binsizes,
    const std::array<int, 3> nbins, const int *FINUFFT_RESTRICT bin_startpts,
    const int *FINUFFT_RESTRICT sortidx, const std::array<const T *, 3> xyz,
    int *FINUFFT_RESTRICT index, const std::array<int, 3> nf) {
  for (int i = threadIdx.x + blockIdx.x * blockDim.x; i < M;
       i += gridDim.x * blockDim.x) {
    const int binidx = compute_bin_index<ndim>(i, nf, inv_binsizes, nbins, xyz);
    storeCacheStreaming(
        index + loadReadOnly(bin_startpts + binidx) + loadReadOnly(sortidx + i), i);
  }
}

// Preparation(?) function for nupts-driven spreading
template<typename T, int ndim>
void cuspread_nuptsdriven_prop(hipfinufft_plan_t<T> &d_plan) {
  if (d_plan.opts.gpu_sort) {
    std::array<int, 3> binsizes = {
        d_plan.opts.gpu_binsizex, d_plan.opts.gpu_binsizey, d_plan.opts.gpu_binsizez};

    auto nbins          = get_nbins<ndim>(d_plan, binsizes);
    const int nbins_tot = nbins_total(nbins);
    const std::array<T, 3> inv_binsizes{T(1) / binsizes[0], T(1) / binsizes[1],
                                              T(1) / binsizes[2]};

    checkHipErrors(hipMemsetAsync(dethrust(d_plan.binsize), 0, nbins_tot * sizeof(int),
                                    d_plan.stream));
    calc_bin_size_noghost<T, ndim>
        <<<(d_plan.M + 1024 - 1) / 1024, 1024, 0, d_plan.stream>>>(
            d_plan.M, d_plan.nf123, inv_binsizes, nbins, dethrust(d_plan.binsize),
            d_plan.kxyz, dethrust(d_plan.sortidx));
    THROW_IF_HIP_ERROR

    thrust::exclusive_scan(thrust::hip::par.on(d_plan.stream), d_plan.binsize.begin(),
                           d_plan.binsize.end(), d_plan.binstartpts.begin());
    THROW_IF_HIP_ERROR

    calc_inverse_of_global_sort_idx<T, ndim>
        <<<(d_plan.M + 1024 - 1) / 1024, 1024, 0, d_plan.stream>>>(
            d_plan.M, inv_binsizes, nbins, dethrust(d_plan.binstartpts),
            dethrust(d_plan.sortidx), d_plan.kxyz, dethrust(d_plan.idxnupts),
            d_plan.nf123);
    THROW_IF_HIP_ERROR
  } else {
    thrust::sequence(thrust::hip::par.on(d_plan.stream), d_plan.idxnupts.begin(),
                     d_plan.idxnupts.begin() + d_plan.M);
    THROW_IF_HIP_ERROR
  }
}

// Subprob spreading kernel
template<typename T, int KEREVALMETH, int ndim, int ns>
__global__ FINUFFT_FLATTEN void spread_subprob(
    const std::array<const T *, 3> xyz, const hip_complex<T> *FINUFFT_RESTRICT c,
    hip_complex<T> *FINUFFT_RESTRICT fw, const int M, const std::array<int, 3> nf,
    const T sigma, const T es_c, const T es_beta, const int *FINUFFT_RESTRICT binstartpts,
    const int *FINUFFT_RESTRICT bin_size, const std::array<int, 3> binsizes,
    const int *FINUFFT_RESTRICT subprob_to_bin,
    const int *FINUFFT_RESTRICT subprobstartpts, const int *FINUFFT_RESTRICT numsubprob,
    const int maxsubprobsize, const std::array<int, 3> nbins,
    const int *FINUFFT_RESTRICT idxnupts) {
  extern __shared__ char sharedbuf[];
  auto fwshared = (hip_complex<T> *)sharedbuf;

  const auto subpidx     = blockIdx.x;
  const auto bidx        = loadReadOnly(subprob_to_bin + subpidx);
  const auto binsubp_idx = subpidx - loadReadOnly(subprobstartpts + bidx);
  const auto ptstart = loadReadOnly(binstartpts + bidx) + binsubp_idx * maxsubprobsize;
  const auto nupts =
      min(maxsubprobsize, loadReadOnly(bin_size + bidx) - binsubp_idx * maxsubprobsize);

  auto offset = compute_offset<ndim>(bidx, nbins, binsizes);

  constexpr auto ns_2       = (ns + 1) / 2;
  constexpr auto rounded_ns = ns_2 * 2;

  int N = 1;
  for (int idim = 0; idim < ndim; ++idim) N *= binsizes[idim] + rounded_ns;

  for (int i = threadIdx.x; i < N; i += blockDim.x) {
    fwshared[i] = {0, 0};
  }

  __syncthreads();

  for (int i = threadIdx.x; i < nupts; i += blockDim.x) {
    const int idx       = ptstart + i;
    const auto nuptsidx = loadReadOnly(idxnupts + idx);
    auto [ker, start]   = get_kerval_and_local_start<T, KEREVALMETH, ndim, ns>(
        nuptsidx, xyz, nf, offset, sigma, es_c, es_beta);

    const auto cnow = loadReadOnly(c + nuptsidx);
    if constexpr (ndim == 1) {
      const auto ofs = start[0] + ns_2;
      for (int xx = 0; xx < ns; ++xx) {
        atomicAddComplexShared<T>(fwshared + xx + ofs, cnow * ker[0][xx]);
      }
    }
    if constexpr (ndim == 2) {
      const auto delta_y = binsizes[0] + rounded_ns;
      const auto ofs0    = (start[1] + ns_2) * delta_y + start[0] + ns_2;
      for (int yy = 0; yy < ns; ++yy) {
        const auto ofs   = ofs0 + yy * delta_y;
        const auto cnowy = cnow * ker[1][yy];
        for (int xx = 0; xx < ns; ++xx) {
          atomicAddComplexShared<T>(fwshared + xx + ofs, cnowy * ker[0][xx]);
        }
      }
    }
    if constexpr (ndim == 3) {
      const auto delta_y = binsizes[0] + rounded_ns;
      const auto delta_z = delta_y * (binsizes[1] + rounded_ns);
      const auto ofs0 =
          (start[2] + ns_2) * delta_z + (start[1] + ns_2) * delta_y + (start[0] + ns_2);
      for (int zz = 0; zz < ns; ++zz) {
        const auto cnowz = cnow * ker[2][zz];
        const auto ofs1  = ofs0 + zz * delta_z;
        for (int yy = 0; yy < ns; ++yy) {
          const auto cnowy = cnowz * ker[1][yy];
          const auto ofs   = ofs1 + yy * delta_y;
          for (int xx = 0; xx < ns; ++xx) {
            atomicAddComplexShared<T>(fwshared + xx + ofs, cnowy * ker[0][xx]);
          }
        }
      }
    }
  }

  __syncthreads();

  /* write to global memory */
  shared_mem_copy_helper<T, ndim, ns>(
      binsizes, offset, nf, [fw, fwshared](int idx_shared, int idx_global) {
        atomicAddComplexGlobal<T>(fw + idx_global, fwshared[idx_shared]);
      });
}

// Subprob spreading CPU driver
template<typename T, int ndim, int ns>
static void cuspread_subprob(const hipfinufft_plan_t<T> &d_plan, int blksize) {
  std::array<int, 3> binsizes = {d_plan.opts.gpu_binsizex, d_plan.opts.gpu_binsizey,
                                       d_plan.opts.gpu_binsizez};
  auto nbins                        = get_nbins<ndim>(d_plan, binsizes);

  const T sigma                = d_plan.spopts.upsampfac;
  const T es_c                 = 4.0 / T(d_plan.spopts.nspread * d_plan.spopts.nspread);
  const T es_beta              = d_plan.spopts.beta;
  const auto sharedplanorysize = shared_memory_required<T>(
      ndim, d_plan.spopts.nspread, d_plan.opts.gpu_binsizex, d_plan.opts.gpu_binsizey,
      d_plan.opts.gpu_binsizez, d_plan.opts.gpu_np);

  const auto launch = [&](auto kernel) {
    hipfinufft_set_shared_memory(kernel, ndim, d_plan);
    for (int t = 0; t < blksize; t++) {
      kernel<<<d_plan.totalnumsubprob, 256, sharedplanorysize, d_plan.stream>>>(
          d_plan.kxyz, d_plan.c + t * d_plan.M, d_plan.fw + t * d_plan.nf, d_plan.M,
          d_plan.nf123, sigma, es_c, es_beta, dethrust(d_plan.binstartpts),
          dethrust(d_plan.binsize), binsizes, dethrust(d_plan.subprob_to_bin),
          dethrust(d_plan.subprobstartpts), dethrust(d_plan.numsubprob),
          d_plan.opts.gpu_maxsubprobsize, nbins, dethrust(d_plan.idxnupts));
      THROW_IF_HIP_ERROR
    }
  };
  if (d_plan.opts.gpu_kerevalmeth)
    launch(spread_subprob<T, 1, ndim, ns>);
  else
    launch(spread_subprob<T, 0, ndim, ns>);
}

static __global__ void calc_subprob(const int *FINUFFT_RESTRICT bin_size,
                                    int *FINUFFT_RESTRICT num_subprob,
                                    const int maxsubprobsize, const int numbins) {
  for (int i = threadIdx.x + blockIdx.x * blockDim.x; i < numbins;
       i += gridDim.x * blockDim.x) {
    num_subprob[i] = (loadReadOnly(bin_size + i) + maxsubprobsize - 1) / maxsubprobsize;
  }
}
static __global__ void map_b_into_subprob(
    int *FINUFFT_RESTRICT d_subprob_to_bin, const int *FINUFFT_RESTRICT d_subprobstartpts,
    const int *FINUFFT_RESTRICT d_numsubprob, const int numbins) {
  for (int i = threadIdx.x + blockIdx.x * blockDim.x; i < numbins;
       i += gridDim.x * blockDim.x) {
    for (int j = 0; j < loadReadOnly(d_numsubprob + i); j++) {
      d_subprob_to_bin[loadReadOnly(d_subprobstartpts + i) + j] = i;
    }
  }
}

// Preparation(?) function for subprob and output-driven spreading
template<typename T, int ndim>
static void cuspread_subprob_and_OD_prop(hipfinufft_plan_t<T> &d_plan) {
  std::array<int, 3> binsizes = {d_plan.opts.gpu_binsizex, d_plan.opts.gpu_binsizey,
                                       d_plan.opts.gpu_binsizez};

  auto nbins          = get_nbins<ndim>(d_plan, binsizes);
  const int nbins_tot = nbins_total(nbins);
  const std::array<T, 3> inv_binsizes{T(1) / binsizes[0], T(1) / binsizes[1],
                                            T(1) / binsizes[2]};

  checkHipErrors(hipMemsetAsync(dethrust(d_plan.binsize), 0, nbins_tot * sizeof(int),
                                  d_plan.stream));
  calc_bin_size_noghost<T, ndim>
      <<<(d_plan.M + 1024 - 1) / 1024, 1024, 0, d_plan.stream>>>(
          d_plan.M, d_plan.nf123, inv_binsizes, nbins, dethrust(d_plan.binsize),
          d_plan.kxyz, dethrust(d_plan.sortidx));
  THROW_IF_HIP_ERROR
  thrust::exclusive_scan(thrust::hip::par.on(d_plan.stream), d_plan.binsize.begin(),
                         d_plan.binsize.end(), d_plan.binstartpts.begin());
  THROW_IF_HIP_ERROR
  calc_inverse_of_global_sort_idx<T, ndim>
      <<<(d_plan.M + 1024 - 1) / 1024, 1024, 0, d_plan.stream>>>(
          d_plan.M, inv_binsizes, nbins, dethrust(d_plan.binstartpts),
          dethrust(d_plan.sortidx), d_plan.kxyz, dethrust(d_plan.idxnupts), d_plan.nf123);
  THROW_IF_HIP_ERROR

  /* --------------------------------------------- */
  //        Determining Subproblem properties      //
  /* --------------------------------------------- */
  calc_subprob<<<(d_plan.M + 1024 - 1) / 1024, 1024, 0, d_plan.stream>>>(
      dethrust(d_plan.binsize), dethrust(d_plan.numsubprob),
      d_plan.opts.gpu_maxsubprobsize, nbins_tot);
  THROW_IF_HIP_ERROR

  thrust::inclusive_scan(thrust::hip::par.on(d_plan.stream), d_plan.numsubprob.begin(),
                         d_plan.numsubprob.begin() + nbins_tot,
                         d_plan.subprobstartpts.begin() + 1);
  THROW_IF_HIP_ERROR

  int totalnumsubprob;
  checkHipErrors(
      hipMemsetAsync(dethrust(d_plan.subprobstartpts), 0, sizeof(int), d_plan.stream));
  checkHipErrors(
      hipMemcpyAsync(&totalnumsubprob, &(dethrust(d_plan.subprobstartpts)[nbins_tot]),
                      sizeof(int), hipMemcpyDeviceToHost, d_plan.stream));
  hipStreamSynchronize(d_plan.stream);
  d_plan.subprob_to_bin.resize(totalnumsubprob);

  map_b_into_subprob<<<(nbins[0] * nbins[1] + 1024 - 1) / 1024, 1024, 0, d_plan.stream>>>(
      dethrust(d_plan.subprob_to_bin), dethrust(d_plan.subprobstartpts),
      dethrust(d_plan.numsubprob), nbins_tot);

  d_plan.totalnumsubprob = totalnumsubprob;
}

/* ---------------------- Output-Driven Kernels -------------------------- */

// Output-driven spreading kernel
template<typename T, int KEREVALMETH, int ndim, int ns>
__global__ FINUFFT_FLATTEN void spread_output_driven(
    const std::array<const T *, 3> xyz, const hip_complex<T> *FINUFFT_RESTRICT c,
    hip_complex<T> *FINUFFT_RESTRICT fw, const int M, const std::array<int, 3> nf,
    const T sigma, const T es_c, const T es_beta, const int *FINUFFT_RESTRICT binstartpts,
    const int *FINUFFT_RESTRICT bin_size, const std::array<int, 3> binsizes,
    const int *FINUFFT_RESTRICT subprob_to_bin,
    const int *FINUFFT_RESTRICT subprobstartpts, const int *FINUFFT_RESTRICT numsubprob,
    const int maxsubprobsize, const std::array<int, 3> nbins,
    const int *FINUFFT_RESTRICT idxnupts, const int np) {
  extern __shared__ char sharedbuf[];

  static constexpr auto ns_2 = (ns + 1) / 2;
  int total                  = 1;
  for (int idim = 0; idim < ndim; ++idim) total *= ns;

  auto [padded_size, local_subgrid_size] = get_padded_subgrid_info<ndim, ns>(binsizes);

  const int bidx        = loadReadOnly(subprob_to_bin + blockIdx.x);
  const int binsubp_idx = blockIdx.x - loadReadOnly(subprobstartpts + bidx);
  const int ptstart     = loadReadOnly(binstartpts + bidx) + binsubp_idx * maxsubprobsize;
  const int nupts =
      min(maxsubprobsize, loadReadOnly(bin_size + bidx) - binsubp_idx * maxsubprobsize);

  auto offset = compute_offset<ndim>(bidx, nbins, binsizes);

  using kernel_data = std::array<std::array<T, ns>, ndim>;
  auto *kerevals    = reinterpret_cast<kernel_data *>(sharedbuf);
  // Offset pointer into sharedbuf after kerevals
  auto *nupts_sm =
      reinterpret_cast<hip_complex<T> *>(sharedbuf + np * sizeof(kernel_data));
  auto *shift = reinterpret_cast<std::array<int, ndim> *>(
      sharedbuf + np * sizeof(kernel_data) + np * sizeof(hip_complex<T>));

  auto *local_subgrid = reinterpret_cast<hip_complex<T> *>(
      sharedbuf + np * sizeof(kernel_data) + np * sizeof(hip_complex<T>) +
      np * sizeof(std::array<int, ndim>));

  // set local_subgrid to zero
  for (int i = threadIdx.x; i < local_subgrid_size; i += blockDim.x) {
    local_subgrid[i] = {0, 0};
  }

  __syncthreads();

  for (int batch_begin = 0; batch_begin < nupts; batch_begin += np) {
    const auto batch_size = min(np, nupts - batch_begin);
    for (int i = threadIdx.x; i < batch_size; i += blockDim.x) {
      const int nuptsidx = loadReadOnly(idxnupts + ptstart + i + batch_begin);
      nupts_sm[i]             = loadReadOnly(c + nuptsidx);
      auto [ker, local_shift] = get_kerval_and_local_start<T, KEREVALMETH, ndim, ns>(
          nuptsidx, xyz, nf, offset, sigma, es_c, es_beta);
      kerevals[i] = ker;
      shift[i]    = local_shift;
    }
    __syncthreads();

    for (auto i = 0; i < batch_size; i++) {
      const auto cnow  = nupts_sm[i];
      const auto start = shift[i];

      for (int idx = threadIdx.x; idx < total; idx += blockDim.x) {
        // strength from shared memory
        int tmp       = idx;
        int idxout    = 0;
        T kervalue    = 1;
        int strideout = 1;
        for (int idim = 0; idim + 1 < ndim; ++idim) {
          int s = tmp % ns;
          kervalue *= kerevals[i][idim][s];
          idxout += strideout * (s + start[idim] + ns_2);
          strideout *= padded_size[idim];
          tmp /= ns;
        }
        // last dimension can be done more cheaply
        kervalue *= kerevals[i][ndim - 1][tmp];
        idxout += strideout * (tmp + start[ndim - 1] + ns_2);

        // Explicit cast disambiguates operator+= overload resolution for hip_complex
        // when both sides are HIP_vector_type<float,2> aliases (HIP 7.1 clang issue).
        const auto contrib = cnow * kervalue;
        local_subgrid[idxout].x += contrib.x;
        local_subgrid[idxout].y += contrib.y;
      }
      __syncthreads();
    }
  }
  /* write to global memory */
  for (int n = threadIdx.x; n < local_subgrid_size; n += blockDim.x) {
    const int outidx =
        output_index_from_flat_local_index<ndim, ns>(n, padded_size, offset, nf);
    atomicAddComplexGlobal<T>(fw + outidx, local_subgrid[n]);
  }
}

// Output-driven spreading CPU driver
template<typename T, int ndim, int ns>
static void cuspread_output_driven(const hipfinufft_plan_t<T> &d_plan, int blksize) {
  std::array<int, 3> binsizes{d_plan.opts.gpu_binsizex, d_plan.opts.gpu_binsizey,
                                    d_plan.opts.gpu_binsizez};
  std::array<int, 3> nbins{1, 1, 1};
  for (int idim = 0; idim < ndim; ++idim)
    nbins[idim] = (d_plan.nf123[idim] + binsizes[idim] - 1) / binsizes[idim];

  const T sigma   = d_plan.spopts.upsampfac;
  const T es_c    = 4.0 / T(d_plan.spopts.nspread * d_plan.spopts.nspread);
  const T es_beta = d_plan.spopts.beta;

  int bufsz = 1;
  for (int idim = 0; idim < ndim; ++idim) bufsz *= ns;

  const auto sharedplanorysize = shared_memory_required<T>(
      ndim, ns, d_plan.opts.gpu_binsizex, d_plan.opts.gpu_binsizey,
      d_plan.opts.gpu_binsizez, d_plan.opts.gpu_np);
  const int nthreads = std::min(256, std::max(bufsz, d_plan.opts.gpu_np));

  const auto launch = [&](auto kernel) {
    hipfinufft_set_shared_memory(kernel, ndim, d_plan);
    THROW_IF_HIP_ERROR
    for (int t = 0; t < blksize; t++) {
      kernel<<<d_plan.totalnumsubprob, nthreads, sharedplanorysize, d_plan.stream>>>(
          d_plan.kxyz, d_plan.c + t * d_plan.M, d_plan.fw + t * d_plan.nf, d_plan.M,
          d_plan.nf123, sigma, es_c, es_beta, dethrust(d_plan.binstartpts),
          dethrust(d_plan.binsize), binsizes, dethrust(d_plan.subprob_to_bin),
          dethrust(d_plan.subprobstartpts), dethrust(d_plan.numsubprob),
          d_plan.opts.gpu_maxsubprobsize, nbins, dethrust(d_plan.idxnupts),
          d_plan.opts.gpu_np);
      THROW_IF_HIP_ERROR
    }
  };
  if (d_plan.opts.gpu_kerevalmeth)
    launch(spread_output_driven<T, 1, ndim, ns>);
  else
    launch(spread_output_driven<T, 0, ndim, ns>);
}

} // namespace spreadinterp
} // namespace hipfinufft
