// AUTO-GENERATED by tools/hipfinufft/cuda_to_hip.py from include/cufinufft/common.h
// Do not edit by hand. Edit the CUDA source and re-run the translator.
#ifndef __COMMON_H__
#define __COMMON_H__

#include <hipfft/hipfft.h>
#include <hipfinufft/hipfinufft_plan_t.h>
#include <hipfinufft_opts.h>
#include <finufft_common/spread_opts.h>
#include <finufft_errors.h>

#include <complex>

namespace hipfinufft {
namespace common {
template<typename T>
void fseries_kernel_compute(
    int dim, std::array<HIPFINUFFT_BIGINT, 3> nf123, const T *d_f, const T *d_phase,
    std::array<gpu_array<T>, 3> &d_fwkerhalf, int ns, hipStream_t stream);
template<typename T>
void nuft_kernel_compute(
    int dim, std::array<HIPFINUFFT_BIGINT, 3> nf123, const T *d_f, const T *d_z,
    std::array<const T *, 3> d_kxyz, std::array<gpu_array<T>, 3> &d_fwkerhalf,
    int ns, hipStream_t stream);

void set_nf_type12(HIPFINUFFT_BIGINT ms, hipfinufft_opts opts, finufft_spread_opts spopts,
                   HIPFINUFFT_BIGINT *nf, HIPFINUFFT_BIGINT b);

template<typename T>
void onedim_fseries_kernel_precomp(HIPFINUFFT_BIGINT nf, T *f, T *a,
                                   finufft_spread_opts opts);
template<typename T>
void onedim_nuft_kernel_precomp(T *f, T *zout, finufft_spread_opts opts);

template<typename T>
std::size_t shared_memory_required(int dim, int ns, int bin_size_x, int bin_size_y,
                                   int bin_size_z, int np);

template<typename T>
void hipfinufft_setup_binsize(int type, int ns, int dim, hipfinufft_opts *opts);

template<typename T, typename V>
void hipfinufft_set_shared_memory(V *kernel, const int dim,
                                 const hipfinufft_plan_t<T> &d_plan) {
  /**
   * WARNING: this function does not handle cuda errors. The caller should check them.
   */
  int shared_mem_per_block{};
  const auto shared_mem_required = shared_memory_required<T>(
      dim, d_plan.spopts.nspread, d_plan.opts.gpu_binsizex, d_plan.opts.gpu_binsizey,
      d_plan.opts.gpu_binsizez, d_plan.opts.gpu_np);
  hipDeviceGetAttribute(&shared_mem_per_block, hipDeviceAttributeSharedMemPerBlockOptin,
                         d_plan.opts.gpu_device_id);
  if (shared_mem_required > unsigned(shared_mem_per_block)) {
    fprintf(stderr,
            "Error: Shared memory required per block is %zu bytes, but the device "
            "supports only %d bytes.\n",
            shared_mem_required, shared_mem_per_block);
    throw int(FINUFFT_ERR_INSUFFICIENT_SHMEM);
  }
  hipFuncSetAttribute(reinterpret_cast<const void *>(kernel),
                       hipFuncAttributeMaxDynamicSharedMemorySize,
                       shared_mem_required);
}

} // namespace common
} // namespace hipfinufft
#endif
