// AUTO-GENERATED by tools/hipfinufft/cuda_to_hip.py from include/cufinufft/defs.h
// Do not edit by hand. Edit the CUDA source and re-run the translator.
#ifndef HIPFINUFFT_DEFS_H
#define HIPFINUFFT_DEFS_H

#include <finufft_common/common.h>
#include <limits>

// FIXME: If hipfft ever takes N > INT_MAX...
constexpr int32_t MAX_NF = std::numeric_limits<int32_t>::max();

#endif
