// AUTO-GENERATED by tools/hipfinufft/cuda_to_hip.py from include/cufinufft/cufinufft_plan_t.h
// Do not edit by hand. Edit the CUDA source and re-run the translator.
#ifndef HIPFINUFFT_PLAN_T_H
#define HIPFINUFFT_PLAN_T_H

#include <array>
#include <hipfft/hipfft.h>
#include <hipfinufft/defs.h>
#include <hipfinufft/types.h>
#include <hipfinufft_opts.h>
#include <finufft_common/spread_opts.h>
#include <finufft_errors.h>
#include <thrust/device_malloc_allocator.h>
#include <thrust/device_ptr.h>
#include <thrust/device_vector.h>
#include <thrust/system/hip/execution_policy.h>
#include <type_traits>

#include <cstddef>
#include <hip/hip_complex.h>

/* This header file contains the internal plan class of hipfinufft,
   as well as other types and functions which are exclusively
   needed in combination with that class. */

template<typename T> inline T *dethrust(thrust::device_ptr<T> ptr) {
  return thrust::raw_pointer_cast(ptr);
}
template<typename T> inline thrust::device_ptr<T> enthrust(T *ptr) {
  return thrust::device_pointer_cast(ptr);
}

class DeviceSwitcher {
private:
  int orig_device;

  static int get_orig_device() noexcept {
    int device{};
    hipGetDevice(&device);
    return device;
  }

public:
  explicit DeviceSwitcher(int newDevice) : orig_device{get_orig_device()} {
    if (hipSetDevice(newDevice) != hipSuccess) throw int(FINUFFT_ERR_HIP_FAILURE);
  }

  ~DeviceSwitcher() {
    if (hipSetDevice(orig_device) != hipSuccess) {
      std::cerr << "failure reverting to original CUDA device; Exiting..." << std::endl;
      std::terminate();
    }
  }
};

template<typename T>
struct ThrustAllocatorAsync : public thrust::device_malloc_allocator<T> {
public:
  using Base      = thrust::device_malloc_allocator<T>;
  using pointer   = typename Base::pointer;
  using size_type = typename Base::size_type;

private:
  hipStream_t stream;
  int deviceID;
  bool pool;

public:
  // Prefer explicit stream; no default ctor needed if you always pass alloc to
  // device_vector
  template<typename U> friend struct ThrustAllocatorAsync;

  explicit ThrustAllocatorAsync(hipStream_t s, int ID, bool supports_pools)
      : stream(s), deviceID(ID), pool(supports_pools) {}

  template<typename U>
  ThrustAllocatorAsync(const ThrustAllocatorAsync<U> &o)
      : stream(o.stream), deviceID(o.deviceID), pool(o.pool) {}

  pointer allocate(size_type n) {
    DeviceSwitcher switcher(deviceID);
    T *p = nullptr;
    auto err =
        pool ? hipMallocAsync(&p, n * sizeof(T), stream) : hipMalloc(&p, n * sizeof(T));
    if (err != hipSuccess) throw int(FINUFFT_ERR_HIP_FAILURE);
    return enthrust(p);
  }

  void deallocate(pointer p, size_type) {
    DeviceSwitcher switcher(deviceID);
    auto err = pool ? hipFreeAsync(dethrust(p), stream) : hipFree(dethrust(p));
    if (err != hipSuccess) { // something went really, really wrong, memory is corrupted
      std::cerr << "error while deallocating GPU memory! Exiting ..." << std::endl;
      std::terminate();
    }
  }
};

template<typename T> using gpu_array = thrust::device_vector<T, ThrustAllocatorAsync<T>>;

template<typename T> inline T *dethrust(gpu_array<T> &arr) {
  return thrust::raw_pointer_cast(arr.data());
}
template<typename T> inline const T *dethrust(const gpu_array<T> &arr) {
  return thrust::raw_pointer_cast(arr.data());
}
template<typename T>
inline std::array<T *, 3> dethrust(std::array<gpu_array<T>, 3> &arr) {
  std::array<T *, 3> res;
  for (int i = 0; i < 3; ++i) res[i] = dethrust(arr[i]);
  return res;
}
template<typename T>
inline std::array<const T *, 3> dethrust(
    const std::array<gpu_array<T>, 3> &arr) {
  std::array<const T *, 3> res;
  for (int i = 0; i < 3; ++i) res[i] = dethrust(arr[i]);
  return res;
}

template<typename T> struct hipfinufft_plan_t {
  // FIXME: we want to make data members private in the future.
  // Not yet possible at the moment, since not all functions working
  // on plans have been converted to members.

  hipfinufft_opts opts;
  bool supports_pools = false;
  finufft_spread_opts spopts;

  ThrustAllocatorAsync<std::byte> alloc{(hipStream_t)opts.gpu_stream, opts.gpu_device_id,
                                        supports_pools};

  int type                                    = 0;
  int dim                                     = 0;
  HIPFINUFFT_BIGINT M                          = 0;
  std::array<HIPFINUFFT_BIGINT, 3> nf123 = {0, 0, 0};
  std::array<HIPFINUFFT_BIGINT, 3> mstu  = {0, 0, 0};
  int ntransf                                 = 0;
  int batchsize                               = 0;
  int iflag                                   = 0;

  int totalnumsubprob                         = 0;
  std::array<gpu_array<T>, 3> fwkerhalf = {
      gpu_array<T>{0, alloc}, gpu_array<T>{0, alloc}, gpu_array<T>{0, alloc}};

  // for type 1,2 it is a pointer to kx, ky, kz (no new allocs), for type 3 it
  // for t3: allocated as "primed" (scaled) src pts x'_j, etc
  std::array<const T *, 3> kxyz     = {nullptr, nullptr, nullptr};
  std::array<gpu_array<T>, 3> kxyzp = {
      gpu_array<T>{0, alloc}, gpu_array<T>{0, alloc}, gpu_array<T>{0, alloc}};
  gpu_array<hip_complex<T>> CpBatch{0, alloc}; // working array of prephased strengths

  // no allocs here
  hip_complex<T> *c = nullptr;
  gpu_array<hip_complex<T>> fwp{0, alloc};
  hip_complex<T> *fw = nullptr;
  hip_complex<T> *fk = nullptr;

  // Type 3 specific
  struct {
    std::array<T, 3> X = {0, 0, 0}, C = {0, 0, 0}, S = {0, 0, 0}, D = {0, 0, 0},
                           h = {0, 0, 0}, gam = {0, 0, 0};
  } type3_params;
  int N                                  = 0; // number of NU freq pts (type 3 only)
  HIPFINUFFT_BIGINT nf                    = 0;
  std::array<const T *, 3> STU     = {nullptr, nullptr, nullptr};
  std::array<gpu_array<T>, 3> STUp = {
      gpu_array<T>{0, alloc}, gpu_array<T>{0, alloc}, gpu_array<T>{0, alloc}};
  T tol = 0;
  // inner type 2 plan for type 3
  hipfinufft_plan_t<T> *t2_plan = nullptr;

  gpu_array<hip_complex<T>> prephase{0, alloc}; // pre-phase, for all input NU pts
  gpu_array<hip_complex<T>> deconv{0, alloc};   // reciprocal of kernel FT, phase, all
                                                 // output NU pts

  // Arrays that used in subprob method
  gpu_array<int> idxnupts{0, alloc};   // length: #nupts, index of the nupts in the
                                       // bin-sorted order
  gpu_array<int> sortidx{0, alloc};    // length: #nupts, order inside the bin the nupt
                                       // belongs to
  gpu_array<int> numsubprob{0, alloc}; // length: #bins,  number of subproblems in each
                                       // bin
  gpu_array<int> binsize{0, alloc}; // length: #bins, number of nonuniform ponits in each
                                    // bin
  gpu_array<int> binstartpts{0, alloc}; // length: #bins, exclusive scan of array binsize
  gpu_array<int> subprob_to_bin{0, alloc}; // length: #subproblems, the bin the subproblem
                                           // works on
  gpu_array<int> subprobstartpts{0, alloc}; // length: #bins, exclusive scan of array
                                            // numsubprob

  // Arrays for 3d (need to sort out)
  gpu_array<int> numnupts{0, alloc};
  gpu_array<int> subprob_to_nupts{0, alloc};

  hipfftHandle fftplan = 0;
  hipStream_t stream = 0;

  bool eps_too_small = false;

  hipfinufft_plan_t() = delete;
  hipfinufft_plan_t(int type_, int dim_, const int *nmodes, int iflag_, int ntransf_,
                   T tol_, const hipfinufft_opts &opts_);
  hipfinufft_plan_t &operator=(hipfinufft_plan_t &) = delete;

  ~hipfinufft_plan_t() {
    DeviceSwitcher switcher(opts.gpu_device_id);
    if (fftplan) hipfftDestroy(fftplan);
    delete t2_plan;
  }

private:
  void alloc1d();
  void alloc2d();
  void alloc3d();

  void alloc1d_nupts();
  void alloc2d_nupts();
  void alloc3d_nupts();

  void exec1(hip_complex<T> *d_c, hip_complex<T> *d_fk);
  void exec2(hip_complex<T> *d_c, hip_complex<T> *d_fk);
  void exec3(hip_complex<T> *d_c, hip_complex<T> *d_fk);

  void deconvolve(int blksize) const;
  template<int modeord, int ndim> void deconvolve_nd(int blksize) const;

  void setpts_12(int M_, const T *d_kx, const T *d_ky, const T *d_kz);
  void allocate();
  void allocate_nupts();

public:
  void setpts(int M_, const T *d_kx, const T *d_ky, const T *d_kz, int N_, const T *d_s,
              const T *d_t, const T *d_u);
  // FIXME: we want to make this "const" in the future
  void exec(hip_complex<T> *d_c, hip_complex<T> *d_fk);
};

#endif
