// AUTO-GENERATED by tools/hipfinufft/cuda_to_hip.py from include/cufinufft/types.h
// Do not edit by hand. Edit the CUDA source and re-run the translator.
#ifndef HIPFINUFFT_TYPES_H
#define HIPFINUFFT_TYPES_H

#include <hipfft/hipfft.h>
#include <hipfinufft/defs.h>
#include <hipfinufft_opts.h>

#include <hip/hip_complex.h>

using HIPFINUFFT_BIGINT = int;

// Marco Barbone 8/5/2024, replaced the ugly trick with std::conditional
// to define hip_complex
// by using std::conditional and std::is_same, we can define hip_complex
// if T is float, hip_complex<T> is hipFloatComplex
// if T is double, hip_complex<T> is hipDoubleComplex
// where hipFloatComplex and hipDoubleComplex are defined in hip/hip_complex.h
// TODO: migrate to cuda/std/complex and remove this
//       Issue: hipfft seems not to support cuda::std::complex
//       A reinterpret_cast should be enough
template<typename T>
using hip_complex = typename std::conditional<
    std::is_same<T, float>::value, hipFloatComplex,
    typename std::conditional<std::is_same<T, double>::value, hipDoubleComplex,
                              void>::type>::type;

template<typename T> static inline constexpr hipfftType_t hipfft_type();
template<> inline constexpr hipfftType_t hipfft_type<float>() { return HIPFFT_C2C; }

template<> inline constexpr hipfftType_t hipfft_type<double>() { return HIPFFT_Z2Z; }

static inline hipfftResult hipfft_ex(hipfftHandle plan, hipfftComplex *idata,
                                   hipfftComplex *odata, int direction) {
  return hipfftExecC2C(plan, idata, odata, direction);
}
static inline hipfftResult hipfft_ex(hipfftHandle plan, hipfftDoubleComplex *idata,
                                   hipfftDoubleComplex *odata, int direction) {
  return hipfftExecZ2Z(plan, idata, odata, direction);
}

#endif
