// AUTO-GENERATED by tools/hipfinufft/cuda_to_hip.py from examples/cuda/example2d3many.cpp
// Do not edit by hand. Edit the CUDA source and re-run the translator.
/* This is an example of performing 2d3many
   in double precision.
*/

#include <complex>
#include <iomanip>
#include <iostream>
#include <math.h>
#include <random>

#include <hipfinufft.h>

#include "../test/utils/norms.hpp"

#include <hip/hip_runtime.h>

static const double PI = 3.141592653589793238462643383279502884;

int main(int argc, char *argv[])
/*
 * example code for 2D Type 3 transformation.
 *
 * To compile the code:
 * hipcc example2d3many.cpp -o example2d3many loc/to/hipfinufft/lib-static/libhipfinufft.a
 * -I/loc/to/hipfinufft/include -lcudart -lhipfft -lnvToolsExt
 *
 * or
 * export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/loc/to/hipfinufft/lib
 * hipcc example2d3many.cpp -example2d3many -L/loc/to/hipfinufft/lib/
 * -I/loc/to/hipfinufft/include -lhipfinufft
 *
 *
 */
{
  std::cout << std::scientific << std::setprecision(3);

  int ier;
  int M            = 10;
  int N            = 20;
  int ntransf      = 4;
  int maxbatchsize = 4;
  int iflag        = 1;
  double tol       = 1e-6;

  double *x, *y, *s, *t;
  std::complex<double> *c, *fk;
  hipHostMalloc(&x, M * sizeof(double));
  hipHostMalloc(&y, M * sizeof(double));
  hipHostMalloc(&s, N * sizeof(double));
  hipHostMalloc(&t, N * sizeof(double));
  hipHostMalloc(&c, M * ntransf * sizeof(std::complex<double>));
  hipHostMalloc(&fk, N * ntransf * sizeof(std::complex<double>));

  double *d_x, *d_y, *d_s, *d_t;
  hipDoubleComplex *d_c, *d_fk;
  hipMalloc(&d_x, M * sizeof(double));
  hipMalloc(&d_y, M * sizeof(double));
  hipMalloc(&d_c, M * ntransf * sizeof(hipDoubleComplex));
  hipMalloc(&d_s, N * sizeof(double));
  hipMalloc(&d_t, N * sizeof(double));
  hipMalloc(&d_fk, N * ntransf * sizeof(hipDoubleComplex));

  std::default_random_engine eng(1);
  std::uniform_real_distribution<double> distr(-1, 1);

  for (int i = 0; i < M; i++) {
    x[i] = PI * distr(eng);
    y[i] = PI * distr(eng);
  }

  for (int i = 0; i < N; i++) {
    s[i] = distr(eng);
    t[i] = distr(eng);
  }

  for (int i = 0; i < M * ntransf; i++) {
    c[i].real(distr(eng));
    c[i].imag(distr(eng));
  }

  hipMemcpy(d_x, x, M * sizeof(double), hipMemcpyHostToDevice);
  hipMemcpy(d_y, y, M * sizeof(double), hipMemcpyHostToDevice);
  hipMemcpy(d_s, s, N * sizeof(double), hipMemcpyHostToDevice);
  hipMemcpy(d_t, t, N * sizeof(double), hipMemcpyHostToDevice);
  hipMemcpy(d_c, c, M * ntransf * sizeof(hipDoubleComplex), hipMemcpyHostToDevice);

  hipfinufft_plan dplan;

  int dim           = 2;
  int64_t nmodes[3] = {N, 1, 1};
  int type          = 3;

  hipfinufft_opts opts;
  hipfinufft_default_opts(&opts);

  ier = hipfinufft_makeplan(type, dim, nmodes, iflag, ntransf, tol, &dplan, &opts);

  ier = hipfinufft_setpts(dplan, M, d_x, d_y, NULL, N, d_s, d_t, NULL);

  ier = hipfinufft_execute(dplan, d_c, d_fk);

  ier = hipfinufft_destroy(dplan);

  hipMemcpy(fk, d_fk, N * ntransf * sizeof(hipDoubleComplex), hipMemcpyDeviceToHost);

  std::cout << std::endl << "Accuracy check:" << std::endl;
  std::complex<double> *fkstart;
  std::complex<double> *cstart;
  for (int tr = 0; tr < ntransf; tr++) {
    fkstart = fk + tr * N;
    cstart  = c + tr * M;
    int jt  = N / 2; // check arbitrary choice of one targ pt
    std::complex<double> J(0, iflag * 1);
    std::complex<double> fkt(0, 0);
    for (int m = 0; m < M; m++) fkt += cstart[m] * exp(J * (s[jt] * x[m] + t[jt] * y[m]));

    printf("[gpu %3d] one targ: rel err in c[%d] is %.3g\n", tr, jt,
           abs(fkstart[jt] - fkt) / infnorm(N, fkstart));
  }

  hipHostFree(x);
  hipHostFree(y);
  hipHostFree(c);
  hipHostFree(fk);

  hipFree(d_x);
  hipFree(d_y);
  hipFree(d_c);
  hipFree(d_fk);
  return 0;
}
