// AUTO-GENERATED by tools/hipfinufft/cuda_to_hip.py from examples/cuda/example2d1many.cpp
// Do not edit by hand. Edit the CUDA source and re-run the translator.
/* This is an example of performing 2d1many
   in single precision.
*/

#include <cmath>
#include <complex>
#include <cstdint>
#include <iomanip>
#include <iostream>
#include <random>

#include "../test/utils/norms.hpp"
#include <hipfinufft.h>

#include <hip/hip_runtime.h>

static const double PI = 3.141592653589793238462643383279502884;

int main(int argc, char *argv[])
/*
 * example code for 2D Type 1 transformation.
 *
 * To compile the code:
 * hipcc example2d1many.cpp -o example2d1many -I/loc/to/hipfinufft/include
 * /loc/to/hipfinufft/lib-static/libhipfinufft.a -lcudart -lhipfft -lnvToolsExt
 *
 * or
 * export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/loc/to/hipfinufft/lib
 * hipcc example2d1many.cpp -o example2d1many -I/loc/to/hipfinufft/include
 * -L/loc/to/hipfinufft/lib/ -lhipfinufft
 *
 *
 */
{
  std::cout << std::scientific << std::setprecision(3);

  int ier;
  int N1      = 256;
  int N2      = 256;
  int M       = 65536;
  int ntransf = 2;
  int iflag   = 1;
  float tol   = 1e-6;

  float *x, *y;
  std::complex<float> *c, *fk;
  hipHostMalloc(&x, M * sizeof(float));
  hipHostMalloc(&y, M * sizeof(float));
  hipHostMalloc(&c, M * ntransf * sizeof(std::complex<float>));
  hipHostMalloc(&fk, N1 * N2 * ntransf * sizeof(std::complex<float>));

  float *d_x, *d_y;
  hipFloatComplex *d_c, *d_fk;
  hipMalloc(&d_x, M * sizeof(float));
  hipMalloc(&d_y, M * sizeof(float));
  hipMalloc(&d_c, M * ntransf * sizeof(hipFloatComplex));
  hipMalloc(&d_fk, N1 * N2 * ntransf * sizeof(hipFloatComplex));

  std::default_random_engine eng(1);
  std::uniform_real_distribution<float> distr(-1, 1);

  for (int i = 0; i < M; i++) {
    x[i] = PI * distr(eng);
    y[i] = PI * distr(eng);
  }

  for (int i = 0; i < M * ntransf; i++) {
    c[i].real(distr(eng));
    c[i].imag(distr(eng));
  }
  hipMemcpy(d_x, x, M * sizeof(float), hipMemcpyHostToDevice);
  hipMemcpy(d_y, y, M * sizeof(float), hipMemcpyHostToDevice);
  hipMemcpy(d_c, c, M * ntransf * sizeof(hipFloatComplex), hipMemcpyHostToDevice);

  hipfinufftf_plan dplan;

  int dim = 2;
  int64_t nmodes[3];
  int type = 1;

  nmodes[0] = N1;
  nmodes[1] = N2;
  nmodes[2] = 1;

  ier = hipfinufftf_makeplan(type, dim, nmodes, iflag, ntransf, tol, &dplan, NULL);

  ier = hipfinufftf_setpts(dplan, M, d_x, d_y, NULL, 0, NULL, NULL, NULL);

  ier = hipfinufftf_execute(dplan, d_c, d_fk);

  ier = hipfinufftf_destroy(dplan);

  hipMemcpy(fk, d_fk, N1 * N2 * ntransf * sizeof(hipFloatComplex),
             hipMemcpyDeviceToHost);

  std::cout << std::endl << "Accuracy check:" << std::endl;
  int N = N1 * N2;
  for (int i = 0; i < ntransf; i += 1) {
    int nt1 = (int)(0.37 * N1), nt2 = (int)(0.26 * N2); // choose some mode index to check
    std::complex<float> Ft = std::complex<float>(0, 0),
                        J  = std::complex<float>(0, 1) * (float)iflag;
    for (auto j = 0UL; j < M; ++j)
      Ft += c[j + i * M] * exp(J * (nt1 * x[j] + nt2 * y[j])); // crude direct
    int it = N1 / 2 + nt1 + N1 * (N2 / 2 + nt2); // index in complex F as 1d array
    printf("[gpu %3d] one mode: abs err in F[%d,%d] is %.3g\n", i, nt1, nt2,
           abs(Ft - fk[it + i * N]));
    printf("[gpu %3d] one mode: rel err in F[%d,%d] is %.3g\n", i, nt1, nt2,
           abs(Ft - fk[it + i * N]) / infnorm(N, fk + i * N));
  }

  hipHostFree(x);
  hipHostFree(y);
  hipHostFree(c);
  hipHostFree(fk);

  hipFree(d_x);
  hipFree(d_y);
  hipFree(d_c);
  hipFree(d_fk);
  return 0;
}
