// AUTO-GENERATED by tools/hipfinufft/cuda_to_hip.py from examples/cuda/example2d2many.cpp
// Do not edit by hand. Edit the CUDA source and re-run the translator.
/* This is an example of performing 2d2many
   in double precision.
*/

#include <complex>
#include <iomanip>
#include <iostream>
#include <cmath>
#include <random>

#include "../test/utils/norms.hpp"
#include <hipfinufft.h>

#include <hip/hip_runtime.h>

static const double PI = 3.141592653589793238462643383279502884;

int main(int argc, char *argv[])
/*
 * example code for 2D Type 1 transformation.
 *
 * To compile the code:
 * hipcc example2d2many.cpp -o example2d2many loc/to/hipfinufft/lib-static/libhipfinufft.a
 * -I/loc/to/hipfinufft/include -lcudart -lhipfft -lnvToolsExt
 *
 * or
 * export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/loc/to/hipfinufft/lib
 * hipcc example2d2many.cpp -L/loc/to/hipfinufft/lib/ -I/loc/to/hipfinufft/include -o
 * example2d1 -lhipfinufft
 *
 *
 */
{
  std::cout << std::scientific << std::setprecision(3);

  int ier;
  int N1           = 128;
  int N2           = 128;
  int M            = 10;
  int ntransf      = 4;
  int maxbatchsize = 4;
  int iflag        = 1;
  double tol       = 1e-6;

  double *x, *y;
  std::complex<double> *c, *fk;
  hipHostMalloc(&x, M * sizeof(double));
  hipHostMalloc(&y, M * sizeof(double));
  hipHostMalloc(&c, M * ntransf * sizeof(std::complex<double>));
  hipHostMalloc(&fk, N1 * N2 * ntransf * sizeof(std::complex<double>));

  double *d_x, *d_y;
  hipDoubleComplex *d_c, *d_fk;
  hipMalloc(&d_x, M * sizeof(double));
  hipMalloc(&d_y, M * sizeof(double));
  hipMalloc(&d_c, M * ntransf * sizeof(hipDoubleComplex));
  hipMalloc(&d_fk, N1 * N2 * ntransf * sizeof(hipDoubleComplex));

  std::default_random_engine eng(1);
  std::uniform_real_distribution<double> distr(-1, 1);

  for (int i = 0; i < M; i++) {
    x[i] = PI * distr(eng);
    y[i] = PI * distr(eng);
  }

  for (int i = 0; i < N1 * N2 * ntransf; i++) {
    fk[i].real(distr(eng));
    fk[i].imag(distr(eng));
  }
  hipMemcpy(d_x, x, M * sizeof(double), hipMemcpyHostToDevice);
  hipMemcpy(d_y, y, M * sizeof(double), hipMemcpyHostToDevice);
  hipMemcpy(d_fk, fk, N1 * N2 * ntransf * sizeof(hipDoubleComplex),
             hipMemcpyHostToDevice);

  hipfinufft_plan dplan;

  int dim = 2;
  int64_t nmodes[3];
  int type = 2;

  nmodes[0] = N1;
  nmodes[1] = N2;
  nmodes[2] = 1;

  hipfinufft_opts opts;
  hipfinufft_default_opts(&opts);
  opts.gpu_maxbatchsize = maxbatchsize;

  ier = hipfinufft_makeplan(type, dim, nmodes, iflag, ntransf, tol, &dplan, &opts);

  ier = hipfinufft_setpts(dplan, M, d_x, d_y, NULL, 0, NULL, NULL, NULL);

  ier = hipfinufft_execute(dplan, d_c, d_fk);

  ier = hipfinufft_destroy(dplan);

  hipMemcpy(c, d_c, M * ntransf * sizeof(hipDoubleComplex), hipMemcpyDeviceToHost);

  std::cout << std::endl << "Accuracy check:" << std::endl;
  std::complex<double> *fkstart;
  std::complex<double> *cstart;
  for (int t = 0; t < ntransf; t++) {
    fkstart = fk + t * N1 * N2;
    cstart  = c + t * M;
    int jt  = M / 2; // check arbitrary choice of one targ pt
    std::complex<double> J(0, iflag * 1);
    std::complex<double> ct(0, 0);
    int m = 0;
    for (int m2 = -(N2 / 2); m2 <= (N2 - 1) / 2; ++m2) // loop in correct order over F
      for (int m1 = -(N1 / 2); m1 <= (N1 - 1) / 2; ++m1)
        ct += fkstart[m++] * exp(J * (m1 * x[jt] + m2 * y[jt])); // crude direct

    printf("[gpu %3d] one targ: rel err in c[%d] is %.3g\n", t, jt,
           abs(cstart[jt] - ct) / infnorm(M, c));
  }

  hipHostFree(x);
  hipHostFree(y);
  hipHostFree(c);
  hipHostFree(fk);

  hipFree(d_x);
  hipFree(d_y);
  hipFree(d_c);
  hipFree(d_fk);
  return 0;
}
