// AUTO-GENERATED by tools/hipfinufft/cuda_to_hip.py from include/cufinufft/contrib/helper_cuda.h
// Do not edit by hand. Edit the CUDA source and re-run the translator.
/* Copyright (c) 2019, NVIDIA CORPORATION. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of NVIDIA CORPORATION nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef COMMON_HELPER_HIP_H_
#define COMMON_HELPER_HIP_H_

#include <cstdio>

#include <finufft_errors.h>

#include <hipfft/hipfft.h>

// This will output the proper CUDA error strings in the event
// that a CUDA host call returns an error
#define checkHipErrors(val) check((val), #val, __FILE__, __LINE__)

#define THROW_IF_HIP_ERROR                                                          \
  {                                                                                  \
    hipError_t err = hipGetLastError();                                            \
    if (err != hipSuccess) {                                                        \
      printf("[%s] Error: %s in %s at line %d\n", __func__, hipGetErrorString(err), \
             __FILE__, __LINE__);                                                    \
      throw int(FINUFFT_ERR_HIP_FAILURE);                                           \
    }                                                                                \
  }

static const char *hipfftGetErrorString(hipfftResult error) {
  switch (error) {
  case HIPFFT_SUCCESS:
    return "HIPFFT_SUCCESS";

  case HIPFFT_INVALID_PLAN:
    return "HIPFFT_INVALID_PLAN";

  case HIPFFT_ALLOC_FAILED:
    return "HIPFFT_ALLOC_FAILED";

  case HIPFFT_INVALID_TYPE:
    return "HIPFFT_INVALID_TYPE";

  case HIPFFT_INVALID_VALUE:
    return "HIPFFT_INVALID_VALUE";

  case HIPFFT_INTERNAL_ERROR:
    return "HIPFFT_INTERNAL_ERROR";

  case HIPFFT_EXEC_FAILED:
    return "HIPFFT_EXEC_FAILED";

  case HIPFFT_SETUP_FAILED:
    return "HIPFFT_SETUP_FAILED";

  case HIPFFT_INVALID_SIZE:
    return "HIPFFT_INVALID_SIZE";

  case HIPFFT_UNALIGNED_DATA:
    return "HIPFFT_UNALIGNED_DATA";

  case HIPFFT_INVALID_DEVICE:
    return "HIPFFT_INVALID_DEVICE";

  case HIPFFT_NO_WORKSPACE:
    return "HIPFFT_NO_WORKSPACE";

  case HIPFFT_NOT_IMPLEMENTED:
    return "HIPFFT_NOT_IMPLEMENTED";

  case HIPFFT_NOT_SUPPORTED:
    return "HIPFFT_NOT_SUPPORTED";

  }

  return "<unknown>";
}

template<typename T>
void check(T result, const char *const func, const char *const file, const int line) {
  if (result) {
    fprintf(stderr, "CUDA error at %s:%d code=%d(%s) \"%s\" \n", file, line,
            static_cast<unsigned int>(result), hipGetErrorName(result), func);
    throw int(FINUFFT_ERR_HIP_FAILURE);
  }
}

#endif // COMMON_HELPER_HIP_H_
