// AUTO-GENERATED by tools/hipfinufft/cuda_to_hip.py from include/cufinufft/contrib/helper_math.h
// Do not edit by hand. Edit the CUDA source and re-run the translator.
#ifndef FINUFFT_INCLUDE_HIPFINUFFT_CONTRIB_HELPER_MATH_H
#define FINUFFT_INCLUDE_HIPFINUFFT_CONTRIB_HELPER_MATH_H

#include <hip/hip_complex.h>

// This header provides some helper functions for hipComplex types.
// It mainly wraps existing CUDA implementations to provide operator overloads
// e.g. cuAdd, cuSub, cuMul, cuDiv, hipCreal, hipCimag, hipCabs, hipCarg, hipConj are all
// provided by CUDA

// Addition for hipDoubleComplex (double) with hipDoubleComplex (double)
__host__ __device__ __forceinline__ hipDoubleComplex operator+(
    const hipDoubleComplex &a, const hipDoubleComplex &b) noexcept {
  return hipCadd(a, b);
}

// Subtraction for hipDoubleComplex (double) with hipDoubleComplex (double)
__host__ __device__ __forceinline__ hipDoubleComplex operator-(
    const hipDoubleComplex &a, const hipDoubleComplex &b) noexcept {
  return hipCsub(a, b);
}

// Multiplication for hipDoubleComplex (double) with hipDoubleComplex (double)
__host__ __device__ __forceinline__ hipDoubleComplex operator*(
    const hipDoubleComplex &a, const hipDoubleComplex &b) noexcept {
  return hipCmul(a, b);
}

// Division for hipDoubleComplex (double) with hipDoubleComplex (double)
__host__ __device__ __forceinline__ hipDoubleComplex operator/(
    const hipDoubleComplex &a, const hipDoubleComplex &b) noexcept {
  return hipCdiv(a, b);
}

// Equality for hipDoubleComplex (double) with hipDoubleComplex (double)
__host__ __device__ __forceinline__ bool operator==(const hipDoubleComplex &a,
                                                    const hipDoubleComplex &b) noexcept {
  return hipCreal(a) == hipCreal(b) && hipCimag(a) == hipCimag(b);
}

// Inequality for hipDoubleComplex (double) with hipDoubleComplex (double)
__host__ __device__ __forceinline__ bool operator!=(const hipDoubleComplex &a,
                                                    const hipDoubleComplex &b) noexcept {
  return !(a == b);
}

// Addition for hipDoubleComplex (double) with double
__host__ __device__ __forceinline__ hipDoubleComplex operator+(const hipDoubleComplex &a,
                                                              double b) noexcept {
  return make_hipDoubleComplex(hipCreal(a) + b, hipCimag(a));
}

__host__ __device__ __forceinline__ hipDoubleComplex operator+(
    double a, const hipDoubleComplex &b) noexcept {
  return make_hipDoubleComplex(a + hipCreal(b), hipCimag(b));
}

// Subtraction for hipDoubleComplex (double) with double
__host__ __device__ __forceinline__ hipDoubleComplex operator-(const hipDoubleComplex &a,
                                                              double b) noexcept {
  return make_hipDoubleComplex(hipCreal(a) - b, hipCimag(a));
}

__host__ __device__ __forceinline__ hipDoubleComplex operator-(
    double a, const hipDoubleComplex &b) noexcept {
  return make_hipDoubleComplex(a - hipCreal(b), -hipCimag(b));
}

// Multiplication for hipDoubleComplex (double) with double
__host__ __device__ __forceinline__ hipDoubleComplex operator*(const hipDoubleComplex &a,
                                                              double b) noexcept {
  return make_hipDoubleComplex(hipCreal(a) * b, hipCimag(a) * b);
}

__host__ __device__ __forceinline__ hipDoubleComplex operator*(
    double a, const hipDoubleComplex &b) noexcept {
  return make_hipDoubleComplex(a * hipCreal(b), a * hipCimag(b));
}

// Division for hipDoubleComplex (double) with double
__host__ __device__ __forceinline__ hipDoubleComplex operator/(const hipDoubleComplex &a,
                                                              double b) noexcept {
  return make_hipDoubleComplex(hipCreal(a) / b, hipCimag(a) / b);
}

__host__ __device__ __forceinline__ hipDoubleComplex operator/(
    double a, const hipDoubleComplex &b) noexcept {
  double denom = hipCreal(b) * hipCreal(b) + hipCimag(b) * hipCimag(b);
  return make_hipDoubleComplex((a * hipCreal(b)) / denom, (-a * hipCimag(b)) / denom);
}

// Addition for hipFloatComplex (float) with hipFloatComplex (float)
__host__ __device__ __forceinline__ hipFloatComplex operator+(
    const hipFloatComplex &a, const hipFloatComplex &b) noexcept {
  return hipCaddf(a, b);
}

// Subtraction for hipFloatComplex (float) with hipFloatComplex (float)
__host__ __device__ __forceinline__ hipFloatComplex operator-(
    const hipFloatComplex &a, const hipFloatComplex &b) noexcept {
  return hipCsubf(a, b);
}

// Multiplication for hipFloatComplex (float) with hipFloatComplex (float)
__host__ __device__ __forceinline__ hipFloatComplex operator*(
    const hipFloatComplex &a, const hipFloatComplex &b) noexcept {
  return hipCmulf(a, b);
}

// Division for hipFloatComplex (float) with hipFloatComplex (float)
__host__ __device__ __forceinline__ hipFloatComplex operator/(
    const hipFloatComplex &a, const hipFloatComplex &b) noexcept {
  return hipCdivf(a, b);
}

// Equality for hipFloatComplex (float) with hipFloatComplex (float)
__host__ __device__ __forceinline__ bool operator==(const hipFloatComplex &a,
                                                    const hipFloatComplex &b) noexcept {
  return hipCrealf(a) == hipCrealf(b) && hipCimagf(a) == hipCimagf(b);
}

// Inequality for hipFloatComplex (float) with hipFloatComplex (float)
__host__ __device__ __forceinline__ bool operator!=(const hipFloatComplex &a,
                                                    const hipFloatComplex &b) noexcept {
  return !(a == b);
}

// Addition for hipFloatComplex (float) with float
__host__ __device__ __forceinline__ hipFloatComplex operator+(const hipFloatComplex &a,
                                                             float b) noexcept {
  return make_hipFloatComplex(hipCrealf(a) + b, hipCimagf(a));
}

__host__ __device__ __forceinline__ hipFloatComplex operator+(
    float a, const hipFloatComplex &b) noexcept {
  return make_hipFloatComplex(a + hipCrealf(b), hipCimagf(b));
}

// Subtraction for hipFloatComplex (float) with float
__host__ __device__ __forceinline__ hipFloatComplex operator-(const hipFloatComplex &a,
                                                             float b) noexcept {
  return make_hipFloatComplex(hipCrealf(a) - b, hipCimagf(a));
}

__host__ __device__ __forceinline__ hipFloatComplex operator-(
    float a, const hipFloatComplex &b) noexcept {
  return make_hipFloatComplex(a - hipCrealf(b), -hipCimagf(b));
}

// Multiplication for hipFloatComplex (float) with float
__host__ __device__ __forceinline__ hipFloatComplex operator*(const hipFloatComplex &a,
                                                             float b) noexcept {
  return make_hipFloatComplex(hipCrealf(a) * b, hipCimagf(a) * b);
}

__host__ __device__ __forceinline__ hipFloatComplex operator*(
    float a, const hipFloatComplex &b) noexcept {
  return make_hipFloatComplex(a * hipCrealf(b), a * hipCimagf(b));
}

// Division for hipFloatComplex (float) with float
__host__ __device__ __forceinline__ hipFloatComplex operator/(const hipFloatComplex &a,
                                                             float b) noexcept {
  return make_hipFloatComplex(hipCrealf(a) / b, hipCimagf(a) / b);
}

__host__ __device__ __forceinline__ hipFloatComplex operator/(
    float a, const hipFloatComplex &b) noexcept {
  float denom = hipCrealf(b) * hipCrealf(b) + hipCimagf(b) * hipCimagf(b);
  return make_hipFloatComplex((a * hipCrealf(b)) / denom, (-a * hipCimagf(b)) / denom);
}

__host__ __device__ __forceinline__ hipDoubleComplex &operator+=(
    hipDoubleComplex &a, const hipDoubleComplex &b) noexcept {
  a = hipCadd(a, b);
  return a;
}

__host__ __device__ __forceinline__ hipDoubleComplex &operator+=(hipDoubleComplex &a,
                                                                double b) noexcept {
  a.x += b;
  return a;
}

__host__ __device__ __forceinline__ hipFloatComplex &operator+=(
    hipFloatComplex &a, const hipFloatComplex &b) noexcept {
  a = hipCaddf(a, b);
  return a;
}

__host__ __device__ __forceinline__ hipFloatComplex &operator+=(hipFloatComplex &a,
                                                               float b) noexcept {
  a.x += b;
  return a;
}

/* Auxiliary func to compute power of complex number */
__device__ __forceinline__ double cabs(const hipDoubleComplex &z) noexcept {
  return double(hipCabs(z));
}

#endif // FINUFFT_INCLUDE_HIPFINUFFT_CONTRIB_HELPER_MATH_H
