// AUTO-GENERATED by tools/hipfinufft/cuda_to_hip.py from include/cufinufft.h
// Do not edit by hand. Edit the CUDA source and re-run the translator.
// Defines the C++/C user interface to HIPFINUFFT library.
#include <hipfft/hipfft.h>

#include <stdint.h>

#include <hipfinufft_opts.h>
#include <finufft_common/defines.h>
#include <finufft_errors.h>

typedef struct hipfinufft_plan_s *hipfinufft_plan;
typedef struct hipfinufft_fplan_s *hipfinufftf_plan;

#ifdef __cplusplus
extern "C" {
#endif
FINUFFT_EXPORT void hipfinufft_default_opts(hipfinufft_opts *opts);

FINUFFT_EXPORT int hipfinufft_makeplan(
    int type, int dim, const int64_t *n_modes, int iflag, int ntr, double eps,
    hipfinufft_plan *d_plan_ptr, const hipfinufft_opts *opts);
FINUFFT_EXPORT int hipfinufftf_makeplan(
    int type, int dim, const int64_t *n_modes, int iflag, int ntr, float eps,
    hipfinufftf_plan *d_plan_ptr, const hipfinufft_opts *opts);

FINUFFT_EXPORT int hipfinufft_setpts(
    hipfinufft_plan d_plan, int64_t M, const double *d_x, const double *d_y,
    const double *d_z, int N, const double *d_s, const double *d_t, const double *d_u);
FINUFFT_EXPORT int hipfinufftf_setpts(
    hipfinufftf_plan d_plan, int64_t M, const float *d_x, const float *d_y,
    const float *d_z, int N, const float *d_s, const float *d_t, const float *d_u);

FINUFFT_EXPORT int hipfinufft_execute(hipfinufft_plan d_plan, hipDoubleComplex *d_c,
                                     hipDoubleComplex *d_fk);
FINUFFT_EXPORT int hipfinufftf_execute(hipfinufftf_plan d_plan, hipFloatComplex *d_c,
                                      hipFloatComplex *d_fk);

FINUFFT_EXPORT int hipfinufft_destroy(hipfinufft_plan d_plan);
FINUFFT_EXPORT int hipfinufftf_destroy(hipfinufftf_plan d_plan);
#ifdef __cplusplus
}
#endif
